/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <math.h>

#include "rnd_types.h"
#include <thrift/c_glib/thrift.h>

/* constants */

/* reads a rnd_service_init_model_args object */
static gint32
rnd_service_init_model_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  RndServiceInitModelArgs * this_object = RND_SERVICE_INIT_MODEL_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
rnd_service_init_model_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  RndServiceInitModelArgs * this_object = RND_SERVICE_INIT_MODEL_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "RndServiceInitModelArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void 
rnd_service_init_model_args_instance_init (RndServiceInitModelArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
}

static void 
rnd_service_init_model_args_finalize (GObject *object)
{
  RndServiceInitModelArgs *tobject = RND_SERVICE_INIT_MODEL_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
rnd_service_init_model_args_class_init (RndServiceInitModelArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = rnd_service_init_model_args_read;
  struct_class->write = rnd_service_init_model_args_write;

  gobject_class->finalize = rnd_service_init_model_args_finalize;
}

GType
rnd_service_init_model_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (RndServiceInitModelArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) rnd_service_init_model_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (RndServiceInitModelArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) rnd_service_init_model_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "RndServiceInitModelArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _RndServiceInitModelResultProperties
{
  PROP_RND_SERVICE_INIT_MODEL_RESULT_0,
  PROP_RND_SERVICE_INIT_MODEL_RESULT_SUCCESS
};

/* reads a rnd_service_init_model_result object */
static gint32
rnd_service_init_model_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  RndServiceInitModelResult * this_object = RND_SERVICE_INIT_MODEL_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_DOUBLE)
        {
          if ((ret = thrift_protocol_read_double (protocol, &this_object->success, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
rnd_service_init_model_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  RndServiceInitModelResult * this_object = RND_SERVICE_INIT_MODEL_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "RndServiceInitModelResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_DOUBLE, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_protocol_write_double (protocol, this_object->success, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
rnd_service_init_model_result_set_property (GObject *object,
                                            guint property_id,
                                            const GValue *value,
                                            GParamSpec *pspec)
{
  RndServiceInitModelResult *self = RND_SERVICE_INIT_MODEL_RESULT (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_INIT_MODEL_RESULT_SUCCESS:
      self->success = g_value_get_double (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
rnd_service_init_model_result_get_property (GObject *object,
                                            guint property_id,
                                            GValue *value,
                                            GParamSpec *pspec)
{
  RndServiceInitModelResult *self = RND_SERVICE_INIT_MODEL_RESULT (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_INIT_MODEL_RESULT_SUCCESS:
      g_value_set_double (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
rnd_service_init_model_result_instance_init (RndServiceInitModelResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = 0;
  object->__isset_success = FALSE;
}

static void 
rnd_service_init_model_result_finalize (GObject *object)
{
  RndServiceInitModelResult *tobject = RND_SERVICE_INIT_MODEL_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
rnd_service_init_model_result_class_init (RndServiceInitModelResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = rnd_service_init_model_result_read;
  struct_class->write = rnd_service_init_model_result_write;

  gobject_class->finalize = rnd_service_init_model_result_finalize;
  gobject_class->get_property = rnd_service_init_model_result_get_property;
  gobject_class->set_property = rnd_service_init_model_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_RND_SERVICE_INIT_MODEL_RESULT_SUCCESS,
     g_param_spec_double ("success",
                          NULL,
                          NULL,
                          -INFINITY,
                          INFINITY,
                          0,
                          G_PARAM_READWRITE));
}

GType
rnd_service_init_model_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (RndServiceInitModelResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) rnd_service_init_model_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (RndServiceInitModelResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) rnd_service_init_model_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "RndServiceInitModelResultType",
                                   &type_info, 0);
  }

  return type;
}

enum _RndServiceVetoArgsProperties
{
  PROP_RND_SERVICE_VETO_ARGS_0,
  PROP_RND_SERVICE_VETO_ARGS_SEED,
  PROP_RND_SERVICE_VETO_ARGS_MODE
};

/* reads a rnd_service_veto_args object */
static gint32
rnd_service_veto_args_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  RndServiceVetoArgs * this_object = RND_SERVICE_VETO_ARGS(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 1:
        if (ftype == T_STRING)
        {
          if (this_object->seed != NULL)
          {
            g_free(this_object->seed);
            this_object->seed = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->seed, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_seed = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      case 2:
        if (ftype == T_STRING)
        {
          if (this_object->mode != NULL)
          {
            g_free(this_object->mode);
            this_object->mode = NULL;
          }

          if ((ret = thrift_protocol_read_string (protocol, &this_object->mode, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_mode = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
rnd_service_veto_args_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  RndServiceVetoArgs * this_object = RND_SERVICE_VETO_ARGS(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "RndServiceVetoArgs", error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "seed", T_STRING, 1, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->seed, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_begin (protocol, "mode", T_STRING, 2, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_string (protocol, this_object->mode, error)) < 0)
    return -1;
  xfer += ret;

  if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
rnd_service_veto_args_set_property (GObject *object,
                                    guint property_id,
                                    const GValue *value,
                                    GParamSpec *pspec)
{
  RndServiceVetoArgs *self = RND_SERVICE_VETO_ARGS (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_VETO_ARGS_SEED:
      if (self->seed != NULL)
        g_free (self->seed);
      self->seed = g_value_dup_string (value);
      self->__isset_seed = TRUE;
      break;

    case PROP_RND_SERVICE_VETO_ARGS_MODE:
      if (self->mode != NULL)
        g_free (self->mode);
      self->mode = g_value_dup_string (value);
      self->__isset_mode = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
rnd_service_veto_args_get_property (GObject *object,
                                    guint property_id,
                                    GValue *value,
                                    GParamSpec *pspec)
{
  RndServiceVetoArgs *self = RND_SERVICE_VETO_ARGS (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_VETO_ARGS_SEED:
      g_value_set_string (value, self->seed);
      break;

    case PROP_RND_SERVICE_VETO_ARGS_MODE:
      g_value_set_string (value, self->mode);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
rnd_service_veto_args_instance_init (RndServiceVetoArgs * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->seed = NULL;
  object->__isset_seed = FALSE;
  object->mode = NULL;
  object->__isset_mode = FALSE;
}

static void 
rnd_service_veto_args_finalize (GObject *object)
{
  RndServiceVetoArgs *tobject = RND_SERVICE_VETO_ARGS (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
  if (tobject->seed != NULL)
  {
    g_free(tobject->seed);
    tobject->seed = NULL;
  }
  if (tobject->mode != NULL)
  {
    g_free(tobject->mode);
    tobject->mode = NULL;
  }
}

static void
rnd_service_veto_args_class_init (RndServiceVetoArgsClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = rnd_service_veto_args_read;
  struct_class->write = rnd_service_veto_args_write;

  gobject_class->finalize = rnd_service_veto_args_finalize;
  gobject_class->get_property = rnd_service_veto_args_get_property;
  gobject_class->set_property = rnd_service_veto_args_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_RND_SERVICE_VETO_ARGS_SEED,
     g_param_spec_string ("seed",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));

  g_object_class_install_property
    (gobject_class,
     PROP_RND_SERVICE_VETO_ARGS_MODE,
     g_param_spec_string ("mode",
                          NULL,
                          NULL,
                          NULL,
                          G_PARAM_READWRITE));
}

GType
rnd_service_veto_args_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (RndServiceVetoArgsClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) rnd_service_veto_args_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (RndServiceVetoArgs),
      0, /* n_preallocs */
      (GInstanceInitFunc) rnd_service_veto_args_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "RndServiceVetoArgsType",
                                   &type_info, 0);
  }

  return type;
}

enum _RndServiceVetoResultProperties
{
  PROP_RND_SERVICE_VETO_RESULT_0,
  PROP_RND_SERVICE_VETO_RESULT_SUCCESS
};

/* reads a rnd_service_veto_result object */
static gint32
rnd_service_veto_result_read (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;
  gchar *name = NULL;
  ThriftType ftype;
  gint16 fid;
  guint32 len = 0;
  gpointer data = NULL;
  RndServiceVetoResult * this_object = RND_SERVICE_VETO_RESULT(object);

  /* satisfy -Wall in case these aren't used */
  THRIFT_UNUSED_VAR (len);
  THRIFT_UNUSED_VAR (data);
  THRIFT_UNUSED_VAR (this_object);

  /* read the struct begin marker */
  if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
  {
    if (name) g_free (name);
    return -1;
  }
  xfer += ret;
  if (name) g_free (name);
  name = NULL;

  /* read the struct fields */
  while (1)
  {
    /* read the beginning of a field */
    if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
    {
      if (name) g_free (name);
      return -1;
    }
    xfer += ret;
    if (name) g_free (name);
    name = NULL;

    /* break if we get a STOP field */
    if (ftype == T_STOP)
    {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == T_DOUBLE)
        {
          if ((ret = thrift_protocol_read_double (protocol, &this_object->success, error)) < 0)
            return -1;
          xfer += ret;
          this_object->__isset_success = TRUE;
        } else {
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return -1;
          xfer += ret;
        }
        break;
      default:
        if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
          return -1;
        xfer += ret;
        break;
    }
    if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }

  if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static gint32
rnd_service_veto_result_write (ThriftStruct *object, ThriftProtocol *protocol, GError **error)
{
  gint32 ret;
  gint32 xfer = 0;

  RndServiceVetoResult * this_object = RND_SERVICE_VETO_RESULT(object);
  THRIFT_UNUSED_VAR (this_object);
  if ((ret = thrift_protocol_write_struct_begin (protocol, "RndServiceVetoResult", error)) < 0)
    return -1;
  xfer += ret;
  if (this_object->__isset_success == TRUE) {
    if ((ret = thrift_protocol_write_field_begin (protocol, "success", T_DOUBLE, 0, error)) < 0)
      return -1;
    xfer += ret;
    if ((ret = thrift_protocol_write_double (protocol, this_object->success, error)) < 0)
      return -1;
    xfer += ret;

    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return -1;
    xfer += ret;
  }
  if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
    return -1;
  xfer += ret;
  if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
    return -1;
  xfer += ret;

  return xfer;
}

static void
rnd_service_veto_result_set_property (GObject *object,
                                      guint property_id,
                                      const GValue *value,
                                      GParamSpec *pspec)
{
  RndServiceVetoResult *self = RND_SERVICE_VETO_RESULT (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_VETO_RESULT_SUCCESS:
      self->success = g_value_get_double (value);
      self->__isset_success = TRUE;
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void
rnd_service_veto_result_get_property (GObject *object,
                                      guint property_id,
                                      GValue *value,
                                      GParamSpec *pspec)
{
  RndServiceVetoResult *self = RND_SERVICE_VETO_RESULT (object);

  switch (property_id)
  {
    case PROP_RND_SERVICE_VETO_RESULT_SUCCESS:
      g_value_set_double (value, self->success);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
      break;
  }
}

static void 
rnd_service_veto_result_instance_init (RndServiceVetoResult * object)
{
  /* satisfy -Wall */
  THRIFT_UNUSED_VAR (object);
  object->success = 0;
  object->__isset_success = FALSE;
}

static void 
rnd_service_veto_result_finalize (GObject *object)
{
  RndServiceVetoResult *tobject = RND_SERVICE_VETO_RESULT (object);

  /* satisfy -Wall in case we don't use tobject */
  THRIFT_UNUSED_VAR (tobject);
}

static void
rnd_service_veto_result_class_init (RndServiceVetoResultClass * cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  ThriftStructClass *struct_class = THRIFT_STRUCT_CLASS (cls);

  struct_class->read = rnd_service_veto_result_read;
  struct_class->write = rnd_service_veto_result_write;

  gobject_class->finalize = rnd_service_veto_result_finalize;
  gobject_class->get_property = rnd_service_veto_result_get_property;
  gobject_class->set_property = rnd_service_veto_result_set_property;

  g_object_class_install_property
    (gobject_class,
     PROP_RND_SERVICE_VETO_RESULT_SUCCESS,
     g_param_spec_double ("success",
                          NULL,
                          NULL,
                          -INFINITY,
                          INFINITY,
                          0,
                          G_PARAM_READWRITE));
}

GType
rnd_service_veto_result_get_type (void)
{
  static GType type = 0;

  if (type == 0) 
  {
    static const GTypeInfo type_info = 
    {
      sizeof (RndServiceVetoResultClass),
      NULL, /* base_init */
      NULL, /* base_finalize */
      (GClassInitFunc) rnd_service_veto_result_class_init,
      NULL, /* class_finalize */
      NULL, /* class_data */
      sizeof (RndServiceVetoResult),
      0, /* n_preallocs */
      (GInstanceInitFunc) rnd_service_veto_result_instance_init,
      NULL, /* value_table */
    };

    type = g_type_register_static (THRIFT_TYPE_STRUCT, 
                                   "RndServiceVetoResultType",
                                   &type_info, 0);
  }

  return type;
}

