/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RND_TYPES_H
#define RND_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* custom thrift includes */

/* begin types */

/* constants */

/* struct RndServiceInitModelArgs */
struct _RndServiceInitModelArgs
{ 
  ThriftStruct parent; 

  /* public */
};
typedef struct _RndServiceInitModelArgs RndServiceInitModelArgs;

struct _RndServiceInitModelArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RndServiceInitModelArgsClass RndServiceInitModelArgsClass;

GType rnd_service_init_model_args_get_type (void);
#define TYPE_RND_SERVICE_INIT_MODEL_ARGS (rnd_service_init_model_args_get_type())
#define RND_SERVICE_INIT_MODEL_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RND_SERVICE_INIT_MODEL_ARGS, RndServiceInitModelArgs))
#define RND_SERVICE_INIT_MODEL_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RND_SERVICE_INIT_MODEL_ARGS, RndServiceInitModelArgsClass))
#define IS_RND_SERVICE_INIT_MODEL_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RND_SERVICE_INIT_MODEL_ARGS))
#define IS_RND_SERVICE_INIT_MODEL_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RND_SERVICE_INIT_MODEL_ARGS))
#define RND_SERVICE_INIT_MODEL_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RND_SERVICE_INIT_MODEL_ARGS, RndServiceInitModelArgsClass))

/* struct RndServiceInitModelResult */
struct _RndServiceInitModelResult
{ 
  ThriftStruct parent; 

  /* public */
  gint8 success;
  gboolean __isset_success;
};
typedef struct _RndServiceInitModelResult RndServiceInitModelResult;

struct _RndServiceInitModelResultClass
{
  ThriftStructClass parent;
};
typedef struct _RndServiceInitModelResultClass RndServiceInitModelResultClass;

GType rnd_service_init_model_result_get_type (void);
#define TYPE_RND_SERVICE_INIT_MODEL_RESULT (rnd_service_init_model_result_get_type())
#define RND_SERVICE_INIT_MODEL_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RND_SERVICE_INIT_MODEL_RESULT, RndServiceInitModelResult))
#define RND_SERVICE_INIT_MODEL_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RND_SERVICE_INIT_MODEL_RESULT, RndServiceInitModelResultClass))
#define IS_RND_SERVICE_INIT_MODEL_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RND_SERVICE_INIT_MODEL_RESULT))
#define IS_RND_SERVICE_INIT_MODEL_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RND_SERVICE_INIT_MODEL_RESULT))
#define RND_SERVICE_INIT_MODEL_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RND_SERVICE_INIT_MODEL_RESULT, RndServiceInitModelResultClass))

/* struct RndServiceVetoArgs */
struct _RndServiceVetoArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * seed;
  gboolean __isset_seed;
  gint32 len;
  gboolean __isset_len;
  gchar * out_file;
  gboolean __isset_out_file;
};
typedef struct _RndServiceVetoArgs RndServiceVetoArgs;

struct _RndServiceVetoArgsClass
{
  ThriftStructClass parent;
};
typedef struct _RndServiceVetoArgsClass RndServiceVetoArgsClass;

GType rnd_service_veto_args_get_type (void);
#define TYPE_RND_SERVICE_VETO_ARGS (rnd_service_veto_args_get_type())
#define RND_SERVICE_VETO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RND_SERVICE_VETO_ARGS, RndServiceVetoArgs))
#define RND_SERVICE_VETO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RND_SERVICE_VETO_ARGS, RndServiceVetoArgsClass))
#define IS_RND_SERVICE_VETO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RND_SERVICE_VETO_ARGS))
#define IS_RND_SERVICE_VETO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RND_SERVICE_VETO_ARGS))
#define RND_SERVICE_VETO_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RND_SERVICE_VETO_ARGS, RndServiceVetoArgsClass))

/* struct RndServiceVetoResult */
struct _RndServiceVetoResult
{ 
  ThriftStruct parent; 

  /* public */
  gint8 success;
  gboolean __isset_success;
};
typedef struct _RndServiceVetoResult RndServiceVetoResult;

struct _RndServiceVetoResultClass
{
  ThriftStructClass parent;
};
typedef struct _RndServiceVetoResultClass RndServiceVetoResultClass;

GType rnd_service_veto_result_get_type (void);
#define TYPE_RND_SERVICE_VETO_RESULT (rnd_service_veto_result_get_type())
#define RND_SERVICE_VETO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RND_SERVICE_VETO_RESULT, RndServiceVetoResult))
#define RND_SERVICE_VETO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_RND_SERVICE_VETO_RESULT, RndServiceVetoResultClass))
#define IS_RND_SERVICE_VETO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RND_SERVICE_VETO_RESULT))
#define IS_RND_SERVICE_VETO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_RND_SERVICE_VETO_RESULT))
#define RND_SERVICE_VETO_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RND_SERVICE_VETO_RESULT, RndServiceVetoResultClass))

#endif /* RND_TYPES_H */
